[ADD] open_academy: New module to manage courses T#59013
geraspace/open_academy_project pull request #1
Opened 2022-07-21 16:36 UTC by geraspace

- Add new model "open.academy.course".
- Add demo data for open.academy.course model.
- Fix some lints.

2022-07-21 16:47 UTC, geraspace commented
@edy1192

2022-07-21 16:58 UTC, edy1192 requested changes

2022-07-21 16:58 UTC, edy1192 commented on open_academy/__manifest__.py
> +
Please remove all blank lines between keys.

```suggestion
'name': "Open Academy",
'summary': """
    Module description""",
```

2022-07-21 16:58 UTC, edy1192 commented on open_academy/controllers/controllers.py
> +
Please don't add commented code.  Remove this file and all the references to it. When you need this you'll add it.

2022-07-21 16:58 UTC, edy1192 commented on open_academy/demo/demo.xml
> +<!--
Same here. Don't add commented code. Please remove this file and all the references to it.

2022-07-21 16:58 UTC, edy1192 commented on open_academy/demo/open_academy_demo.xml
> +      <field name="name">Curso Nikon</field>
All the code must be in English please.

```suggestion
      <field name="name">Nikon Course</field>
```

2022-07-21 16:58 UTC, edy1192 commented on open_academy/demo/open_academy_demo.xml
> +      <field name="name">Curso Canon</field>
Same here, English please.

2022-07-21 16:58 UTC, edy1192 commented on open_academy/demo/open_academy_demo.xml
> +      <field name="name">Curso Leica</field>
Same here, English please.

2022-07-21 16:58 UTC, edy1192 commented on open_academy/models/__init__.py
> +from . import open_academy
Please name the file like the model. 

```suggestion
from . import open_academy_course
```
It is a standard that allows us to know which model is being added or modified, just by looking at the file name.

2022-07-21 16:58 UTC, edy1192 commented on open_academy/models/open_academy.py
> +
Remember change the file name please.

2022-07-21 16:58 UTC, edy1192 commented on open_academy/views/templates.xml
> +<!--
Same here. Don't add commented code. Please remove this file and all the references to it.

2022-07-21 16:58 UTC, edy1192 commented on open_academy/views/views.xml
> +<!--
Same here. Don't add commented code. Please remove this file and all the references to it.

2022-07-21 17:00 UTC, edy1192 commented
Hi @geraspace revision done. 

If you have any doubts you could ask me. 

Regards.

2022-07-21 17:15 UTC, edy1192 commented on open_academy/__manifest__.py
> +    'name': "Open Academy",
Please keep consistent if you will use single quote do it everywhere, same for double quotes, a good practice it's use double quotes.

2022-07-21 17:20 UTC, edy1192 requested changes

2022-07-21 17:20 UTC, edy1192 commented on open_academy/__manifest__.py
> +    'depends': ['base'],
```suggestion
    'depends': [
    'base',
    ],
```

2022-07-21 17:20 UTC, edy1192 commented on open_academy/__init__.py
> +from . import controllers
Controllers are not needed at this point, so remove the import and also the folder

2022-07-21 17:20 UTC, edy1192 commented on open_academy/__init__.py
> +from . import demo
There's no a "demo.py" file, this is for import models (python's files)

2022-07-21 23:24 UTC, edy1192 requested changes

2022-07-21 23:24 UTC, edy1192 commented on open_academy/demo/open_academy_demo.xml
> +<?xml version="1.0" encoding="utf-8"?>
Please rename this file `open_academy_course_demo.xml`

2022-07-22 01:15 UTC, geraspace commented
Hi @edy1192, could you check the update please? And thank you!

2022-07-22 16:30 UTC, edy1192 requested changes

2022-07-22 16:30 UTC, edy1192 commented on open_academy/__manifest__.py
> +    'name': "Open Academy",
This change is pending. Please use double quotes

```suggestion
    "name": "Open Academy",
```

2022-07-22 16:30 UTC, edy1192 commented on open_academy/demo/demo.xml
> +<!--
This change is pending. Remove this file please and its reference in `__manifest__.py` file.

2022-07-22 16:32 UTC, edy1192 commented
Hi @geraspace There are 2 pending comments, please apply them and let me know again to review.

Regards.

2022-07-22 18:40 UTC, geraspace commented
@edy1192 I think it's ready now.

2022-07-22 18:49 UTC, edy1192 approved these changes

2022-07-22 18:50 UTC, edy1192 commented
Thank you @geraspace

2022-07-22 18:50 UTC, merged