[IMP] open_academy: Add program to test web services T#59013
geraspace/open_academy_project pull request #10
Opened 2022-08-17 16:14 UTC by geraspace

- Display sessions, and their corresponding number of seats.
- Create a new session for one of the courses.

- Fix start and end dates in session model.

2022-08-17 16:14 UTC, geraspace commented
Good morning, @edy1192. Here's the web service PR. Thank you!

2022-08-17 20:56 UTC, edy1192 requested changes

2022-08-17 20:56 UTC, edy1192 commented on open_academy/web_services/ws.py
> +instructor_name = "Brandon Freeman"
You could create a dictionary with this 

```suggestion
session_data = {
    "name": "Nikon II",
    "course_id": course_id,
    "instructor_id": instructor_id,
    "duration": 1,
    "seats": 5,
}
```

2022-08-17 20:56 UTC, edy1192 commented on open_academy/web_services/ws.py
> +)
Use the dictionary `session_data`.
```suggestion
id = models.execute_kw(db, uid, password, 'open.academy.session', 'create', session_data)
```

2022-08-17 20:56 UTC, edy1192 commented on open_academy/web_services/ws.py
> +    "attendee_ids": [7, 3]
Never add harcoded ID's, please. I learned it after my first review.

Read about the special commands to update o2m and m2m fields [here](https://www.odoo.com/documentation/14.0/developer/reference/addons/orm.html#odoo.models.Model.write)

Then use that to add the attendee_id in the dictionary.

2022-08-17 20:56 UTC, edy1192 commented on open_academy/web_services/ws.py
> +                                 'search_read', [], {'fields': ['name']})
You just need one course and one instructor.
```suggestion
course_id = models.execute_kw(db, uid, password, 'open.academy.course',
                                 'search', [], {'limit': 1})
instructor_id = models.execute_kw(db, uid, password, 'res.partner',
                                     'search', [[['instructor', '=', True]]],
                                     {'limit': 1})
attendee_id = models.execute_kw(db, uid, password, 'res.partner',
                                 'search', [], {'limit': 1})
```

2022-08-17 20:56 UTC, edy1192 commented on open_academy/web_services/ws.py
> +    print(instructor["name"])
With the search and limit 1 you don't need this.

2022-08-18 02:09 UTC, geraspace commented
@edy1192 I think it is working now :) Thanks!

2022-08-18 15:10 UTC, edy1192 approved these changes

2022-08-18 15:11 UTC, merged