[IMP] open_academy: Add sessions and instructor field in contact T#59013
geraspace/open_academy_project pull request #4
Opened 2022-08-03 21:21 UTC by geraspace

- Add new page "sessions" in contact
- Add "instructor" boolean field inside "sessions" page
- Add session records inside "sessions" page

2022-08-03 21:23 UTC, geraspace commented
Hello, @edy1192. This is the inheritance exercise. Thanks!

2022-08-03 21:51 UTC, edy1192 requested changes

2022-08-03 21:51 UTC, edy1192 commented on open_academy/models/partner.py
> +from odoo import models, fields
Please rename this file and its references. The standard is 
![image](https://user-images.githubusercontent.com/11479473/182205005-64414316-e298-49a4-a419-3c03825f0d58.png) and the model is `res.partner` so the file should be `res_partner.py`

2022-08-03 21:51 UTC, edy1192 commented on open_academy/views/partner_views.xml
> +<?xml version="1.0" encoding="utf-8"?>
Please rename this file. Should be `res_partner_views.xml`

![image](https://user-images.githubusercontent.com/11479473/182206968-2bc77453-6e02-4a7b-b1c5-3c140606c010.png)

2022-08-03 21:51 UTC, edy1192 commented on open_academy/views/partner_views.xml
> +    <record model="ir.ui.view" id="partner_view_form">
As a good practice we use the same id than original record and add the suffix `_inherit` to indicates that is an inheritance. 

```suggestion
    <record model="ir.ui.view" id="view_partner_form_inherit">
```

2022-08-03 21:51 UTC, edy1192 commented on open_academy/views/partner_views.xml
> +        <field name="name">partner.view.form</field>
```suggestion
        <field name="name">view.partner.form.inherit</field>
```

2022-08-03 21:51 UTC, edy1192 commented on open_academy/models/partner.py
> +    instructor = fields.Boolean(default=False)
Boolean fields are `False` by default, the `default` attribute it's not necessary.

2022-08-03 21:51 UTC, edy1192 commented on open_academy/models/partner.py
> +class Partner(models.Model):
As a good practice we use the same name that the parent model.

```suggestion
class ResPartner(models.Model):
```

2022-08-03 21:51 UTC, edy1192 commented on open_academy/models/partner.py
> +    session_ids = fields.Many2many("open.academy.session", readonly=True)
As a good practice we always place for the name of the relation, the name of both models and the suffix `_rel`. The first name is current model and the second is related model.

```suggestion
    sessions_ids = fields.Many2many("open.academy.session", "res_partner_session_rel")
```

Please apply this comment in `open.academy.session` model to the `many2many` field.

2022-08-04 02:06 UTC, geraspace commented
I pushed the changes. I believe it's okay now, @edy1192.

2022-08-04 14:07 UTC, edy1192 approved these changes

2022-08-04 14:07 UTC, merged

2022-08-04 14:07 UTC, edy1192 commented
Hi @geraspace Merged 👍🏼