[IMP] open_academy: Graph, kanban and security T#59013
geraspace/open_academy_project pull request #7
Opened 2022-08-10 21:46 UTC by geraspace

Here is a new PR, @edy1192. Thanks! : )

2022-08-10 22:41 UTC, edy1192 requested changes

2022-08-10 22:41 UTC, edy1192 commented on open_academy/security/security.xml
> +    <record id="open_academy_rule_manager" model="ir.rule">
```suggestion
    <record id="open_academy_rule_responsible_can_modify" model="ir.rule">
```

2022-08-10 22:41 UTC, edy1192 commented on open_academy/security/security.xml
> +        <field name="name">You can only modify a course if you are the responsible</field>
The code must be generic, we do not name things with you, us, them...
```suggestion
        <field name="name">Only responsible can modify a course</field>
```

2022-08-10 22:43 UTC, edy1192 requested changes

2022-08-10 22:43 UTC, edy1192 commented on open_academy/security/security.xml
> +        </field>
```suggestion
        <field name="domain_force">['|', ('responsible_id','=',False), ('responsible_id','=',user.id)]</field>
```

2022-08-10 22:44 UTC, edy1192 commented on open_academy/security/security.xml
> +        <field name="perm_unlink" eval="1" />
```suggestion
        <field name="perm_read" eval="False"/>
        <field name="perm_write" eval="True"/>
        <field name="perm_create" eval="False"/>
        <field name="perm_unlink" eval="True" />
```

2022-08-11 00:41 UTC, geraspace commented
@edy1192 I think it's okay now : )

2022-08-11 15:31 UTC, edy1192 requested changes

2022-08-11 15:31 UTC, edy1192 commented on open_academy/security/security.xml
> +        <field name="groups" eval="[(4, ref('open_academy.open_academy_group_manager'))]"/>
```suggestion
        <field name="groups" eval="[Command.link(ref('open_academy.open_academy_group_manager'))]"/>
```

2022-08-11 15:54 UTC, geraspace commented
Good morning, @edy1192. I just made the change.

2022-08-11 16:04 UTC, edy1192 approved these changes

2022-08-11 16:04 UTC, merged