[IMP] open_academy: Wizard to register attendees for sessions T#59013
geraspace/open_academy_project pull request #8
Opened 2022-08-12 01:36 UTC by geraspace

- Add wizard to register new attendees to one or various sessions

2022-08-12 01:37 UTC, geraspace commented
@edy1192 here is a short PR for the wizard. Thanks!

2022-08-12 16:28 UTC, edy1192 requested changes

2022-08-12 16:28 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard.py
> +        return self.env["open.academy.session"].browse(self._context.get("active_ids"))
Move this method after field's declaration. See [guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#37models) `In a Model attribute order should be` 

When you move this method you'll get an error. You just use the lambda function to call the method in field's attribute.

`default=lambda self: self._default_sessions()`

2022-08-12 16:28 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard.py
> +    attendee_wizard_ids = fields.Many2many("res.partner")
Don't add `wizard` to field's name.

```suggestion
    session_ids = fields.Many2many('open.academy.session', default=_default_sessions)
    attendee_ids = fields.Many2many("res.partner")
```

2022-08-12 16:28 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard_views.xml
> +                    <button name="subscribe" type="object" string="Finish" class="oe_highlight"/>
```suggestion
                <footer>
                    <button name="subscribe" type="object" string="Add Attendees" class="oe_highlight"/>
```

2022-08-12 16:28 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard_views.xml
> +        <field name="name">Add atendees to session</field>
```suggestion
        <field name="name">Add attendees to sessions</field>
```

2022-08-12 16:39 UTC, geraspace commented
Hi, @edy1192 I think it's ready!

2022-08-12 16:49 UTC, edy1192 requested changes

2022-08-12 16:49 UTC, edy1192 commented on open_academy/i18n/es_MX.po
> +# Translation of Odoo Server.
Use es.po file please. Remember what I said yesterday.

2022-08-12 16:49 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard.py
> +    _description = "Quick registration of attendees to sessions"
```suggestion
    _description = "open.academy.wizard"
```

2022-08-12 16:49 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard.py
> +            session.attendee_ids |= self.attendee_wizard_ids
Did you test this?

You changed the field's name, so this is wrong.

2022-08-12 16:49 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard_views.xml
> +                <field name="attendee_wizard_ids" string="Attendees"/>
Same here. This fields do not exists anymore.

Please test your changes before ask for revision.

2022-08-12 17:00 UTC, geraspace commented
You are right, I don't know why I did not test, @edy1192. Now it's working, and I also added the translation to the commit message. Thanks!

2022-08-12 21:36 UTC, edy1192 requested changes

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Un instructor no puede ser un asistente"
```suggestion
msgstr "Un instructor no puede ser un asistente."
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Fecha de creación"
```suggestion
msgstr "Creado el"
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "ID"
When terms are similar between languages the msgtr is empty.

```suggestion
msgstr ""
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Instructor"
Same here, leave it empty please.

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Fecha de última modificación"
```suggestion
msgstr "Última modificación el"
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Fecha de última actualización"
```suggestion
msgstr "Última actualización el"
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Gestor"
```suggestion
msgstr "Administrador"
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "El título del curso debe ser diferente a la descripción"
```suggestion
msgstr "El título del curso debe ser diferente a la descripción."
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "El título del curso debe ser único"
```suggestion
msgstr "El título del curso debe ser único."
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "El numero de asistentes no puede ser mayor al número de asientos disponibles."
```suggestion
msgstr "El número de asistentes no puede ser mayor al número de asientos disponibles."
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "El número de asientos no puede ser negativo."
```suggestion
msgstr "El número de asientos no puede ser menor a 0."
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard.py
> +    _description = "Quick registration of attendees to sessions"
This change is missing

2022-08-12 21:36 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard.py
> +                                   default=lambda self: self._default_sessions())
See this https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#33idioms

```suggestion
    session_ids = fields.Many2many(
                                   'open.academy.session',
                                   default=lambda self: self._default_sessions())
```

2022-08-12 21:36 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard_views.xml
> +                    <button name="subscribe" type="object" string="Add attendees" class="oe_highlight"/>
This term is missing in translation.

2022-08-12 21:36 UTC, edy1192 commented on open_academy/wizards/open_academy_wizard_views.xml
> +        <field name="name">Add attendees to sessions</field>
Same here, missing in es.po file

2022-08-13 18:21 UTC, geraspace commented
I hope it's okay now, @edy1192. Thanks :)

2022-08-15 15:04 UTC, edy1192 requested changes

2022-08-15 15:04 UTC, edy1192 commented on open_academy/i18n/es.po
> +"                                    Duración:"
```suggestion
"                                    duración:"
```

2022-08-15 16:02 UTC, geraspace commented
I think those should have been uppercased, :) thanks, @edy1192. It can be checked now.

2022-08-15 17:03 UTC, edy1192 approved these changes

2022-08-15 17:03 UTC, merged